client_config_backend: settings
client_config:
  client_id: 880025712165-i2as65q9porclivpopjfoiadj3n71i8c.apps.googleusercontent.com
  client_secret: kLu5tGmy9wEt5PifuFw2UPDY

save_credentials: True
save_credentials_backend: file
save_credentials_file: ../data/googledrive/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install